# -*- coding: utf-8 -*-
"""Mental Health Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vKal3WJT1rPAtLeOnXwL2lQAdXLAt7y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('survey.csv')

df.head()

df.tail()

df.info()

"""# Hadling the Missing Values"""

df['Age'].unique()

# Age Column fixed to accomodate proper age criteria.

df = df[(df['Age'] > 0) & (df['Age'] <= 120)]

# Fixing the Gender column to proper order.

df['Gender'].unique()

# Drop the State Column as only USA states where mentioned where as the data is from all over the world.

df = df.drop('state', axis=1)

# Filling the Work Interferance column with missing values

df['work_interfere'] = df['work_interfere'].fillna('Unknown')

df['self_employed'].unique()

df['self_employed'] = df['self_employed'].fillna('Unknown')

df['obs_consequence'].unique()

df = df.drop('comments', axis=1)

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

# 1. Age Distribution
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
df['Age'].hist(bins=30, color='skyblue', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')

# 2. Gender Distribution
plt.subplot(1, 2, 2)
df['Gender'].value_counts().plot(kind='bar', color='coral')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Work Interfere Impact
plt.figure(figsize=(10, 5))
df['work_interfere'].value_counts().plot(kind='bar', color='lightgreen')
plt.title('Mental Health Interference at Work')
plt.xlabel('Interference Level')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# 4. Self Employed vs Work Interfere

plt.figure(figsize=(10, 5))
pd.crosstab(df['self_employed'], df['work_interfere']).plot(kind='bar')
plt.title('Self Employed vs Work Interference')
plt.xlabel('Self Employed')
plt.ylabel('Count')
plt.legend(title='Work Interfere')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x='work_interfere', y='Age', data=df, palette='Set2')
plt.title('Age vs Mental Health Work Interference')
plt.xlabel('Work Interference')
plt.ylabel('Age')
plt.show()

print(df.columns.tolist())

# 1. Family History Distribution
plt.figure(figsize=(10, 5))
df['family_history'].value_counts().plot(kind='bar', color='purple')
plt.title('Family History of Mental Health Issues')
plt.xlabel('Family History')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# 2. Treatment Distribution
plt.figure(figsize=(10, 5))
df['treatment'].value_counts().plot(kind='bar', color='orange')
plt.title('Seeking Treatment for Mental Health')
plt.xlabel('Treatment')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# 3. Company Size Distribution
plt.figure(figsize=(10, 5))
df['no_employees'].value_counts().plot(kind='bar', color='teal')
plt.title('Company Size (Number of Employees)')
plt.xlabel('Number of Employees')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# 4. Remote Work Distribution
plt.figure(figsize=(10, 5))
df['remote_work'].value_counts().plot(kind='bar', color='cyan')
plt.title('Remote Work Opportunity')
plt.xlabel('Remote Work Available')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# 5. Tech Company Distribution
plt.figure(figsize=(10, 5))
df['tech_company'].value_counts().plot(kind='bar', color='lime')
plt.title('Work in Tech Company')
plt.xlabel('Tech Company')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()